# Generated by Django 4.2.4 on 2024-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikereservation',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bikereservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
