# Generated by Django 4.2.4 on 2024-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bikereservation_finish_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeparkzone',
            old_name='occupied_slot',
            new_name='occupied_slots',
        ),
        migrations.RenameField(
            model_name='bikeparkzone',
            old_name='total_slot',
            new_name='total_slots',
        ),
        migrations.RenameField(
            model_name='bikeparkzone',
            old_name='vacant_slot',
            new_name='vacant_slots',
        ),
        migrations.RenameField(
            model_name='carparkzone',
            old_name='occupied_slot',
            new_name='occupied_slots',
        ),
        migrations.RenameField(
            model_name='carparkzone',
            old_name='total_slot',
            new_name='total_slots',
        ),
        migrations.RenameField(
            model_name='heavyparkzone',
            old_name='occupied_slot',
            new_name='occupied_slots',
        ),
        migrations.RenameField(
            model_name='heavyparkzone',
            old_name='total_slot',
            new_name='total_slots',
        ),
        migrations.RenameField(
            model_name='heavyparkzone',
            old_name='vacant_slot',
            new_name='vacant_slots',
        ),
        migrations.RemoveField(
            model_name='carparkzone',
            name='vacant_slot',
        ),
        migrations.AddField(
            model_name='carparkzone',
            name='vacant_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
