# Generated by Django 4.2.4 on 2024-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bikereservation_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyreservation',
            name='parking_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.heavyparkzone'),
        ),
    ]
