# Generated by Django 4.2.4 on 2024-03-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_heavyreservation_parking_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='heavyreservation',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='heavyreservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
