# Generated by Django 4.2.4 on 2024-03-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_carreservation_finish_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_slots', models.PositiveIntegerField()),
                ('vacant_slots', models.PositiveIntegerField(default=0)),
                ('occupied_slots', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('heavy', 'Heavy Vehicle')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, max_length=6, null=True)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('plate_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=16)),
                ('checked_out', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('heavy', 'Heavy Vehicle')], max_length=10, verbose_name='Vehicle Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkzone')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='bikereservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bikereservation',
            name='parking_zone',
        ),
        migrations.RemoveField(
            model_name='carparkzone',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='carreservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='carreservation',
            name='parking_zone',
        ),
        migrations.RemoveField(
            model_name='heavyparkzone',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='heavyreservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='heavyreservation',
            name='parking_zone',
        ),
        migrations.DeleteModel(
            name='BikeParkZone',
        ),
        migrations.DeleteModel(
            name='BikeReservation',
        ),
        migrations.DeleteModel(
            name='CarParkZone',
        ),
        migrations.DeleteModel(
            name='CarReservation',
        ),
        migrations.DeleteModel(
            name='HeavyParkZone',
        ),
        migrations.DeleteModel(
            name='HeavyReservation',
        ),
    ]
